// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class CourseInstructor
{
    public int CrsId { get; set; }

    public int InstId { get; set; }

    public virtual Course Crs { get; set; } = null!;

    public virtual Instructor Inst { get; set; } = null!;
}