// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class Course
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public int? Duration { get; set; }

    public string? Description { get; set; }

    public int? TopId { get; set; }

    public virtual ICollection<CourseInstructor> CourseInstructors { get; set; } = new List<CourseInstructor>();

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();

    public virtual Topic? Top { get; set; }
}