// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class Department
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public DateOnly? HiringDate { get; set; }

    public int? InsId { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}