// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class Instructor
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Address { get; set; }

    public int? Bouns { get; set; }

    public int? Salary { get; set; }

    public int? HourRate { get; set; }

    public int? DepId { get; set; }

    public virtual ICollection<CourseInstructor> CourseInstructors { get; set; } = new List<CourseInstructor>();

    public virtual Department? Dep { get; set; }
}