// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataBaseFirst.Models;

public partial class ITIDBContext : DbContext
{
    public ITIDBContext()
    {
    }

    public ITIDBContext(DbContextOptions<ITIDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CourseInstructor> CourseInstructors { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<StudCourse> StudCourses { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-3P0T45J3;Initial Catalog=ITIDB;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__courses__3214EC079BF9E245");

            entity.ToTable("courses");

            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
            entity.Property(e => e.TopId).HasColumnName("top_id");

            entity.HasOne(d => d.Top).WithMany(p => p.Courses)
                .HasForeignKey(d => d.TopId)
                .HasConstraintName("fk_Top_Id");
        });

        modelBuilder.Entity<CourseInstructor>(entity =>
        {
            entity.HasKey(e => new { e.CrsId, e.InstId }).HasName("PK__Course_I__5226759AC6A85B44");

            entity.ToTable("Course_Instructors");

            entity.Property(e => e.CrsId).HasColumnName("Crs_Id");
            entity.Property(e => e.InstId).HasColumnName("Inst_Id");

            entity.HasOne(d => d.Crs).WithMany(p => p.CourseInstructors)
                .HasForeignKey(d => d.CrsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Course_In__Crs_I__47DBAE45");

            entity.HasOne(d => d.Inst).WithMany(p => p.CourseInstructors)
                .HasForeignKey(d => d.InstId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Course_In__Inst___48CFD27E");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC0792A81810");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.HiringDate).HasColumnName("Hiring_Date");
            entity.Property(e => e.InsId).HasColumnName("Ins_Id");
            entity.Property(e => e.Name).IsUnicode(false);
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Instruct__3214EC07788D29C6");

            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.DepId).HasColumnName("Dep_id");
            entity.Property(e => e.HourRate).HasColumnName("Hour_Rate");
            entity.Property(e => e.Name).IsUnicode(false);

            entity.HasOne(d => d.Dep).WithMany(p => p.Instructors)
                .HasForeignKey(d => d.DepId)
                .HasConstraintName("FK__Instructo__Dep_i__3C69FB99");
        });

        modelBuilder.Entity<StudCourse>(entity =>
        {
            entity.HasKey(e => new { e.StudId, e.CrsId }).HasName("PK__Stud_Cou__4CC2072C8825DC28");

            entity.ToTable("Stud_Course");

            entity.Property(e => e.StudId).HasColumnName("Stud_Id");
            entity.Property(e => e.CrsId).HasColumnName("Crs_Id");

            entity.HasOne(d => d.Crs).WithMany(p => p.StudCourses)
                .HasForeignKey(d => d.CrsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Stud_Cour__Crs_I__44FF419A");

            entity.HasOne(d => d.Stud).WithMany(p => p.StudCourses)
                .HasForeignKey(d => d.StudId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Stud_Cour__Stud___440B1D61");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Students__3214EC077B571643");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.DepId).HasColumnName("Dep_id");
            entity.Property(e => e.Fname).IsUnicode(false);
            entity.Property(e => e.Lname).IsUnicode(false);

            entity.HasOne(d => d.Dep).WithMany(p => p.Students)
                .HasForeignKey(d => d.DepId)
                .HasConstraintName("fk_Dep_Id");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__topics__3214EC07B1B3B1C0");

            entity.ToTable("topics");

            entity.Property(e => e.Name).IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}