// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class Student
{
    public int Id { get; set; }

    public string? Fname { get; set; }

    public string? Lname { get; set; }

    public int? Age { get; set; }

    public string? Address { get; set; }

    public int? DepId { get; set; }

    public virtual Department? Dep { get; set; }

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();
}