// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class StudCourse
{
    public int StudId { get; set; }

    public int CrsId { get; set; }

    public virtual Course Crs { get; set; } = null!;

    public virtual Student Stud { get; set; } = null!;
}